defaults:
  - meta_base

cls:
  _target_: methods.relationnet.RelationNet

  layers_size: ???
  dropout: ???
  batch_norm: ??? # 0 to disable, 1 to enable

# The algorithm is fast to converge
stop_epoch: 30

name: relationnet
